* Sprint 3: Kubernetes Layer Extraction Experiment

Started: 2026-02-14

** Plan

- [X] Refine plan according to phases in the ~b-ops~ repository.
- [X] Research how others handle shared Kustomize bases across repos
- [X] Deployment of the bootstrap folder
  - Deployment of Manifests
  - Deployment of cluster specific secrets
- [X] Deployment of cluster specific settings / secret settings
- [X] Push the repository into the internal Gitea service
- [X] Kick off Flux, focus on cluster ~dev-env~
- [X] Test kluctl for the bootstrap deployment
- [X] Add applications into ~business-operations~ and use in ~dev-env~
  - [X] ~cloudnative-pg~ may be an good start, does not need cluster specific
    customization
    - use an app from ~business-operations~ without tweaking it
  - [X] ~echoserver~ is as simple as it gets
    - use an app and have cluster specific configuration applied
    - Configuration just works
  - [X] ~hajimari~ uses a few variables out of the cluster settings
    - use an app and have cluster specific configuration applied
    - [X] deployment
    - [X] Needs custom values for the Helm chart
  - [X] ~lldap~ needs a volume
    - prepare for the backup / restore experiments later
  - [X] ~forgejo~ or ~synapse~ use a database
    - prepare for the backup / restore experiments later
- [X] re-run full dev cluster from scratch into minikube to verify latest changes
- [X] Test out Kustomize component for backup and restore handling
  - [X] ~lldap~ needs a volume, could be suitable for this
  - [X] ~forgejo~ could be an good candidate as well
    - https://code.forgejo.org/forgejo-helm/forgejo-helm as a Helm chart
      - [X] activate backup
      - [X] re-create cluster from scratch with restore on
      - [X] check if the data did arrive in ~forgejo~ and if it is fully functional
  - [X] ~synapse~ out of ~cluster-exp~ uses both database and volume, without
    being an internal chart or image.
    - skipped for now
- [X] re-run full dev cluster from scratch into minikube to verify latest changes
  - works, needs a few manual tweaks regarding the cluster revision / database revision
- [ ] review - The Flux Kustomization points to the Git Repository by name,
  consider to replace by a better value than the current ~bv-ops-kubernetes~.
- [ ] review - The namespace handling is odd, compare ~network~ which requires
  ~base-apps~ when keeping the original structure.
- [ ] update and re-run full demo-ops cluster
- [ ] --- refine below this point
- [ ] Update ~demo-ops~ or provide builtin ~dev-env~ for ~business-operations~
- [ ] Consider: Create a second internal repository for ~business-operations~ in
  the internal Gitea
- [ ] Experiment: explore multi-repo approaches for Flux/Kustomize layer
- [ ] Experiment: try out most promising approaches with VolSync
  templates
- [ ] Experiment: explore Taskfile pattern for cluster tasks (push to
  internal Gitea)
- [ ] Document findings and decide on the approach

** Review and Backlog

- [ ] Dependency pinning for ~ansible~, ~nixos~ and ~kubernetes~.
  - Ideally this should use the same mechanism.
- [ ] Usage of *Ansible*. If the inventory is maintained in Nix already, then it
  may be possible to replace the Ansible setup with simple scripts and have one
  tool less in the chain.
- [ ] Usage of *Kluctl*. Both bootstrap and also the FluxCD part could be
  simplified using Kluctl and a push based approach.

** Focus

Discover how to split the Kubernetes layer out of ~b-ops~ into
~business-operations~.

The details of the phases are documented in ~b-ops~ within the file
~docs/kubernetes/bootstrap-overview.rst~.

** Checkpoint

- Dev and demo cluster fully deployable based on a split setup.

** Notes

*** Backup / Restore handling

**** Volumes

The current state just did work based on the Kustomize components.

Tested with ~lldap~.

**** Databases

The ~cloudnative-pg~ operator needs a twist: The backup runs into a S3 bucket
with a given server name.

When restoring, the restore must be done with this particular server name, and
the backup configuration must point to a new server name.

The reason is that otherwise it would start to put the WAL backup into the same
bucket, potentially overwriting the existing data.

This means that every restore needs an update of the backup server name, e.g.
appending a "backup-revision". The restore configuration will have to be
adjusted after the fact.

If the restore is made for the whole application or the whole cluster, then the
existing parameter ~cluster_revision~ has to be incremented. And after the fact
the ~cluster_boostrap_revision~ has to be adjusted as well.

For the database this currently means that both the cluster level revision and
the database level revision are included into the server name.

*** ~cloudnative-pg~ split

**** Options

- Point to a Git URL in the `resources` of
  `kubernetes/dev-env/apps/kustomization.yaml`
- Deploy a Flux Kustomization which points into the ~business-operations~
  repository via a ~GitRepository~ resource.
- Expect ~business-operations~ in a subpath of the ~b-ops~ repository.
  - This is using either submodules or Flux' include mechanism.

**** Ways of using

***** Unmodified from upstream

Could be a Flux Kustomization pointing into the other repository's
Kustomization, like in bootstrap.

A well-known path within the repository would also work without issues. This
would be a submodule or a source combination.

***** Modified

Does require a local Kustomization.

This uses the ~resources~ to point to remote sources, or it depends on the other
repository to be available in a well-known path within the repository, either by
submodule or by include.

**** Submodule vs. Flux' Include

In both cases the ~b-ops~ repository points into the ~business-operations~
repository:

- A submodule points into the commit.
- A Flux Include based combination points into a reference, which can be a
  commit but also could be a moving target like a branch name.

For now a constraint would be that only one version of ~business-operations~ can
be pointed into. This would be different if the Kustomization of the respective
application or building block would point directly into ~business-operations~.

If ever needed for a particular case, this can always be modeled this way as an
exception. Alternative approaches could be to branch off in
~business-operations~ in a fork and use that instead. Also having two versions
included would be an option.

The inclusion mechanism does not affect ~business-operations~, only the using
repository like ~b-ops~ would be affected, so that experimenting with the
approaches does not affect the shared repository in a negative way. The decision
how to use and include is completely inside the using repository.

**** Hint: Dependency Management

From the experimentation so far there is a clear hint that a mechanism for
dependency management will be eventually needed.

It seems that it should support a fine granular combination of building blocks
in some way. Somewhat similar to how modern package managers include a bunch of
libraries and support freezing / locking dependencies to a particular version.

It may be that a generic tool like Nix could help here to combine the fragments
in a way so that the result forms a directory tree which tooling like Kustomize,
Kluctl or Flux could as input.

This should be delayed as much as possible to better understand the real needs
first.

*** Kluctl testrun

Using Kluctl does put additional constraints around the setup which are mainly
relevant for development.

For the bootstrap case, it does not allow a Kustomization to refer to sources
outside of the project directory.

One reason seems to be that Kluctl first runs a "rendering" phase to apply
the Jinja 2 templating, and the result is then processed via Kustomize. The
local reference then simply does not resolve anymore.

It seems to walk up the directory tree to detect a git repository as the root to
copy files.

Trying to find out if there are approaches available which I did not yet
discover: https://github.com/kluctl/kluctl/discussions/1421.

**** Conclusion

- Usage for the bootstrap phase works nicely.
- Templating could allow to make the bootstrap already configurable in
  ~business-operations~.
- Unclear how a good local setup for fast iteration would look like. One option
  could be to consider a git submodule like approach.

*** First deployment via bootstrap playbook

With a stub inventory it is possible to run the bootstrap playbook into any
cluster. Used the ~dev-env~ cluster for a small scale test.

FluxCD did start up as intended, only Gitea did not deploy due to the missing
reference into the ~business-operations~ repository. At this stage this is
expected because soling this problem is one of the steps after the boostrap.

Only challenge left is that the Kustomization points into ~business-operations~
and needs some for of reference for this.

*** Dependencies

**** Overview

- ~ansible~ folder
  - Using currently the shell out of ~business-operations~
- ~nixos~ folder
  - Input of a Nix Flake.
  - Dev: Point to a local clone of ~business-operations~ with builtin tooling of
    Nix.
- ~bootstrap~ folder
  - Points into ~business-operations~ from a Kustomization.
  - Dev: Point to a local clone of ~business-operations~ instead.
- FluxCD
  - Has a ~GitRepository~ source pointing to a reference of
    ~business-operations~.

**** Approach for ~bootstrap~

This is all handled in the CLI, basically client side.

Tweaking the path in the Kustomization or even defining the overlay twice, once
as a dev variant to expect a local clone.

**** Approach for FluxCD

The ~GitRepository~ lives in ~b-ops~ and should pin down the exact reference as
tag or commit.

An update would be done by updating ~b-ops~ which sets the reference.

Development would benefit from a changed URL, either pointing into a fork of
~business-operations~ or even pointing to a fork in the internal Gitea instance.

The drawback of pointing into a reference like ~main~ or another branch name
would be that this is impossible (or at least fairly involved) to reproduce in
retrospect.

**** ~kluctl~ inspection

It does have the concept of overriding the git urls, this would solve the issue
in a similar way how nix is solving it with flake input overrides.

On the layer of it's custom ~Deployment~ object it does support git urls and oci
urls.

Apart from that most other parts are based on plain ~Kustomizations~.

***** Conclusion

The direct support for SOPS and the support for overriding git inputs would make
it a very good fit for the bootstrap part instead of plain ~kubectl~.

The ~nixpkgs~ version is up to date, using it would not involve a lot of tweaks.

**** Conclusion

- Start with depending on the local clone being next to the ~b-ops~ repo.
- Split and make it work.
- Test if kluctl can help here.
- The way how the dependency is pinned should ideally be the same, e.g.
  ~ansible~, ~nixos~ and ~kubernetes~ should all use the same version of the
  upstream repository.

*** Bootstrap folder

**** Research ~kluctl~

It has the concept of library deployments which can be imported. This could be
interesting.

See: https://kluctl.io/docs/kluctl/kluctl-libraries/

**** Content

***** Manifests

The bootstrap folder's *manifests* are not specific per instance. These can be used
directly out of ~business-operations~. The deployment of these is a one off.

#+begin_notes
The bootstrap seems to be specific to the usage of FluxCD.

It would not be needed if a push model would be used, like a ~kluctl~ setup
could do.
#+end_notes

***** Secrets

There are a few secrets deployed, these are all instance specific.

***** Kustomization

Tweaks components as needed. For development the storage class is currently
tweaked out.

*** FluxCD

**** GitRepository

The field ~spec.ref~ is most relevant. It allows to specify a commit reference
via ~spec.ref.commit~.

This could be one way to include ~business-operations~ into the local
repository. The ~GitRepository~ reference would be managed in the ~b-ops~
repository. This does need a Git commit per update and effectively makes
~business-operations~ a "submodule" of ~b-ops~.

Compare also ~.spec.recurseSubmodules~.

See: https://fluxcd.io/flux/components/source/gitrepositories/

**** External Artifact

- Allows to have artifacts produced by an external system.

See: https://fluxcd.io/flux/components/source/externalartifacts/

**** Artifact Generator

- Allows to compose multiple artifacts together.

See: https://fluxcd.io/flux/components/source/artifactgenerators/

*** Overview ~b-ops~

Looking at the following "phases" as described in the ~b-ops~ bootstrap overview:

- *Base infrastructure*
  - This is covered already from sprint 2.
- *Bootstrap*
  - This is about making FluxCD operational and providing a Git server so that
    FluxCD can start to take over.
  - Could aim for an empty cluster modeled after the ~dev-env~ setup.
  - Allows to "git push" into the cluster, and Flux will reconcile.
- *Base Apps*
  - Groups together the applications which are required so
    that the cluster is fully able to manage itself.
  - Examples: Vault, External Secrets, Gitlab, Volsync, Flux Webhook, Snapshot
    Controller, DNS, Rook-Ceph
- *Apps*
  - Everything else.

The current setup is already layered.

Only the layer *Apps* is expected to be customized.

*Base Apps* is still somewhat unclear, esp. since it does have "heavy" content
like Gitlab, Rook-Ceph and Vault.

Ideally the layered concept can stay to some degree.

The *Apps* part should eventually be split in some way, so that it is possible
to decide which apps to install. It should be possible to also bring one's own
apps without a need to be clued into the mono repository on the long run.

*** Bootstrap phase

**** Pre-conditions

- Cluster is working and can be accessed via ~kubectl~.

**** Steps

- Deploy ~bootstrap~ folder via ~kustomize~.
- Deploy the cluster's age key.
- Deploy Gitea bootstrap secret.
- Wait until Gitea has deen initialized and configured.
- Push repository into Gitea.
- Deploy cluster settings and secret settings.
- Kick off Flux by deploying ~flux/config~ via ~kustomize~.

Note: ~kustomize~ means ~kubectl apply --server-side --kustomize~.

*** Base apps phase

This is already purely done via Flux.

** Learnings and Insights

*** Kustomize and patching

Some applications are set up with common configuration and then adjustments for
the particular case.

One example is hajimari which supports a set of bookmarks to be configured
through its Helm values and a list of namespaces to observe.

The list of namespaces is a list of string values. With the strategic patches
such lists can only be replaced but not appended to.

As a workaround either copy the list or use the JSON patches instead.


** Closing Status
