* Sprint 3: Kubernetes Layer Extraction Experiment

Started: 2026-02-14

** Plan

- [X] Refine plan according to phases in the ~b-ops~ repository.
- [X] Research how others handle shared Kustomize bases across repos
- [X] Deployment of the bootstrap folder
  - Deployment of Manifests
  - Deployment of cluster specific secrets
- [X] Deployment of cluster specific settings / secret settings
- [X] Push the repository into the internal Gitea service
- [X] Kick off Flux, focus on cluster ~dev-env~
- [X] Test kluctl for the bootstrap deployment
- [X] Add applications into ~business-operations~ and use in ~dev-env~
  - [X] ~cloudnative-pg~ may be an good start, does not need cluster specific
    customization
    - use an app from ~business-operations~ without tweaking it
  - [X] ~echoserver~ is as simple as it gets
    - use an app and have cluster specific configuration applied
    - Configuration just works
  - [X] ~hajimari~ uses a few variables out of the cluster settings
    - use an app and have cluster specific configuration applied
    - [X] deployment
    - [X] Needs custom values for the Helm chart
  - [X] ~lldap~ needs a volume
    - prepare for the backup / restore experiments later
  - [X] ~forgejo~ or ~synapse~ use a database
    - prepare for the backup / restore experiments later
- [X] re-run full dev cluster from scratch into minikube to verify latest changes
- [X] Test out Kustomize component for backup and restore handling
  - [X] ~lldap~ needs a volume, could be suitable for this
  - [X] ~forgejo~ could be an good candidate as well
    - https://code.forgejo.org/forgejo-helm/forgejo-helm as a Helm chart
      - [X] activate backup
      - [X] re-create cluster from scratch with restore on
      - [X] check if the data did arrive in ~forgejo~ and if it is fully functional
  - [X] ~synapse~ out of ~cluster-exp~ uses both database and volume, without
    being an internal chart or image.
    - skipped for now
- [X] re-run full dev cluster from scratch into minikube to verify latest changes
  - works, needs a few manual tweaks regarding the cluster revision / database revision
- [X] review - The Flux Kustomization points to the Git Repository by name,
  consider to replace by a better value than the current ~bv-ops-kubernetes~.
  - not a big issue now, can be done after the splitting
- [X] Prepare test deployment based on virtual machines
- [X] Consider: Create a second internal repository for ~business-operations~ in
  the internal Gitea
  - not needed for now, using submodules at the moment avoids this need
- [X] Experiment: explore multi-repo approaches for Flux/Kustomize layer
- [X] Experiment: try out most promising approaches with VolSync
  templates
- [X] Document findings and decide on the approach

** Review and Backlog

All moved into backlog.

** Focus

Discover how to split the Kubernetes layer out of ~b-ops~ into
~business-operations~.

The details of the phases are documented in ~b-ops~ within the file
~docs/kubernetes/bootstrap-overview.rst~.

** Checkpoint

- Dev and demo cluster fully deployable based on a split setup.

** Notes

*** Conclusions

**** Submodule usage

This is fine for the purpose. The "instance" repository of a cluster points into
~business-operations~ based on a commit hash.

This glues the nixos, ansible and the kubernetes layer in the same way.

***** Conclusion

Keep as-is for now to be able to finish the split first.

**** Backup / Restore

The current implementation does depend on the concept of "revision" values on
the cluster level, and for the database also on the database level:

- ~cluster_revision~
- ~backup-revision~ for the database.
  - Done as annotation in the experiments with the app ~forgejo~. Implicit in
    most other cases by being hardcoded.

And for retore:

- ~cluster_bootstrap_revision~
- ~restore-revision~

The current cluster settings have a few more parameters which are related and
add the concept that there are "stages" of the state for backup and restore.
These correspond to S3 buckets at the moment.

The original idea is that a cluster ~prod~ does backup into ~prod~ and restore
from ~prod~. Then a cluster ~acceptance~ would restore from ~prod~ but backup
into ~acceptance~ to ensure that no data from testing an update would go into
the production backups. There has also been the idea of a ~dev~ stage which can
read from ~acceptance~ and backup into ~dev~. This concept does currently miss a
distinction between "production" data and "test" data. The naive staging
currently allows data from "production" to end up in "dev".

Current settings from the config map:

#+begin_src yaml
  cluster_revision: "1"
  cluster_bootstrap_mode: restore
  cluster_bootstrap_revision: "28"
  cluster_bootstrap_revision_vault: "1"
  cluster_bootstrap_revision_certificates: null

  cluster_backup_env: dev
  cluster_restore_env: acceptance
  cluster_restore_certificates_env: dev

  cnpg_backup_base_path: dev-cnpg
  cnpg_restore_base_path: acceptance-cnpg
  #+end_src


***** Conclusion

Keep as-is for now, to allow the split to be finished first. Afterwards this
will have to be re-worked.

**** Flux usage

***** Overview

The current setup is based on the idea that a Flux Kustomization is deployed per
"thing": Typically this is the application, often also one for the application
and one per needed dependency like volumes or database services.

This Kustomization points into a path within the source repository (The cluster
repository with the included submodule) and renders the content via Kustomize.

Most applications use a Helm chart. A Flux HelmChart object is deployed from
within the Kustomize folder so that Flux will eventually use Helm to deploy the
chart.

Kustomize is used for post processing of the Helm chart itself when needed.

***** Adjusting configuration of a part

The cluster instance has to decide which parts to include. This means there has
to be a pointer from the cluster instance into ~business-operations~ via
Kustomize.

Example fragment:

#+begin_src yaml
  ---
  apiVersion: kustomize.config.k8s.io/v1beta1
  kind: Kustomization
  resources:
    - ../../../external/business-operations/kubernetes/apps/database
    - ../../../external/business-operations/kubernetes/base-apps/network/ns
    - ../../../external/business-operations/kubernetes/apps/network
#+end_src

These directories will typically deploy a Flux Kustomization which then again
points into the ~business-operations~ directory.

This approach makes adjustments difficult. Either the above Kustomization would
have to patch the generated Flux Kustomization, so that it either points into a
different path or so that it contains patches to tweak the generated resources.
Or the alternative would be to copy the Flux Kustomization into the cluster's
repository and adjust it there.

****** Example using a copy of the Flux Kustomization

From the Forgejo experiment:

#+begin_src yaml
  apiVersion: kustomize.toolkit.fluxcd.io/v1
  kind: Kustomization
  metadata:
    name: cluster-apps-forgejo-db
    namespace: flux-system
  spec:
    # NOTE: Some content left out
    patches:
      - patch: |
          - op: replace
            path: /spec/externalClusters/0/barmanObjectStore/serverName
            value: db-rev1
          - op: remove
            path: /spec/backup
        target:
          kind: Cluster
    postBuild:
      substitute:
        cnpg_restore_base_path: "dev-cnpg"
        cluster_bootstrap_revision: "1"
#+end_src

This example removes the backup completely for experimentation and tweaks a few
of the cluster settings via ~postBuild.substitute~.

This is difficult to understand and difficult to test locally. ~flux build~ does
allow to do this, but it is very tricky.

Most likely it would have been better to patch the ~path~ instead already via
Kustomize so that it points into the cluster's repository.

****** Using Kustomize from within the cluster's repository

The adjustments can be done from within the cluster's repository directly on the
Kustomize layer when changing the path.

The following example shows a few tweaks applied to the default setup of the
ingress controller:

#+begin_src yaml
  apiVersion: kustomize.config.k8s.io/v1beta1
  kind: Kustomization
  namespace: network
  resources:
    - ../../../../../external/business-operations/kubernetes/base-apps/network/ingress-nginx/app

  patches:
    - target:
        kind: HelmRelease
        name: ingress-nginx
      patch: |
        # NOTE: Needed when there is no LoadBalancer support for the cluster.
        - op: add
          path: /spec/values/controller/service/type
          value: NodePort
        # NOTE: Disable Authelia
        - op: remove
          path: /spec/values/controller/config/global-auth-url
#+end_src

This Kustomization adjusts the Flux level HelmRelease, if tweaks to the
generated manifests would be needed, then the patch would have to add post
processing into the HelmRelease instance. This again would be difficult to
understand.

During the experiments there was no way to test out what the result of the Helm
chart deployment would look like without going though the cluster.

***** Conclusion

For now this will stay as-is, accepting the fragility and complexity so that the
split can be finished first.

The observed problems indicate that an alternative approach which can be
rendered without the cluster directly on the CLI would be valuable.

It also indicates that the structure is not quite right yet for a situation
where there is a shared code which is then used from within an cluster
repository.

**** Variable substitution

This did just work also with the split. The way how it works is not easy to
understand though. The first Flux Kustomization applies patches to all other
Flux Kustomizations so that they will apply both the variable substitution and
also the patching if they render new Flux Kustomizations.

***** Example

#+begin_src yaml
  apiVersion: kustomize.toolkit.fluxcd.io/v1
  kind: Kustomization
  metadata:
    name: cluster
    namespace: flux-system
  spec:
    # NOTE: Other details left out

    patches:
      - patch: |-
          apiVersion: kustomize.toolkit.fluxcd.io/v1
          kind: Kustomization
          metadata:
            name: not-used
            namespace: not-used
          spec:
            decryption:
              provider: sops
              secretRef:
                name: sops-age
            postBuild:
              substituteFrom:
                - kind: ConfigMap
                  name: cluster-settings
                - kind: Secret
                  name: secret-cluster-settings
        target:
          group: kustomize.toolkit.fluxcd.io
          kind: Kustomization
          labelSelector: substitution.flux.home.arpa/disabled notin (true)
    postBuild:
      substituteFrom:
        - kind: ConfigMap
          name: cluster-settings
        - kind: Secret
          name: secret-cluster-settings
#+end_src

***** Conclusion

For now this will stay. Special needs which require tweaking per part can be
satisfied based on the approaches found in the Forgejo tests.

Long term this should be improved. This may solve itself in case Flux would be
replaced by a CLI tool.

**** Kustomize

The usage of Kustomize within the current ~b-ops~ repository is not structured
in a way so that it would leverage Kustomize's features fully.

There is a bit of a challenge to discover these features due to the
documentation of Kustomize being not fully up to date and a bit scattered. Some
aspects can only be found through the examples within the repository.

***** Discovered resources online

There were quite a few suggestions from the community online, regarding
Kustomize the following is relevant:

- https://git.shivering-isles.com/shivering-isles/infrastructure-gitops/-/tree/main/shared/components?ref_type=heads

***** Conclusion

Where applicable and needed aim to improve the Kustomize setup, so that
adjustments per cluster instance are easier.

The Forgejo experiments found that using annotations may help to configure
components like the database backup and restore.

Potentially also the local configuration annotation could be useful together
with the config map generator to make cluster wide configuration available on
the Kustomize layer and allow to merge into this configuration from an overlay.
This has not been tried yet.


*** Backup / Restore handling

**** Volumes

The current state just did work based on the Kustomize components.

Tested with ~lldap~.

**** Databases

The ~cloudnative-pg~ operator needs a twist: The backup runs into a S3 bucket
with a given server name.

When restoring, the restore must be done with this particular server name, and
the backup configuration must point to a new server name.

The reason is that otherwise it would start to put the WAL backup into the same
bucket, potentially overwriting the existing data.

This means that every restore needs an update of the backup server name, e.g.
appending a "backup-revision". The restore configuration will have to be
adjusted after the fact.

If the restore is made for the whole application or the whole cluster, then the
existing parameter ~cluster_revision~ has to be incremented. And after the fact
the ~cluster_boostrap_revision~ has to be adjusted as well.

For the database this currently means that both the cluster level revision and
the database level revision are included into the server name.

*** ~cloudnative-pg~ split

**** Options

- Point to a Git URL in the `resources` of
  `kubernetes/dev-env/apps/kustomization.yaml`
- Deploy a Flux Kustomization which points into the ~business-operations~
  repository via a ~GitRepository~ resource.
- Expect ~business-operations~ in a subpath of the ~b-ops~ repository.
  - This is using either submodules or Flux' include mechanism.

**** Ways of using

***** Unmodified from upstream

Could be a Flux Kustomization pointing into the other repository's
Kustomization, like in bootstrap.

A well-known path within the repository would also work without issues. This
would be a submodule or a source combination.

***** Modified

Does require a local Kustomization.

This uses the ~resources~ to point to remote sources, or it depends on the other
repository to be available in a well-known path within the repository, either by
submodule or by include.

**** Submodule vs. Flux' Include

In both cases the ~b-ops~ repository points into the ~business-operations~
repository:

- A submodule points into the commit.
- A Flux Include based combination points into a reference, which can be a
  commit but also could be a moving target like a branch name.

For now a constraint would be that only one version of ~business-operations~ can
be pointed into. This would be different if the Kustomization of the respective
application or building block would point directly into ~business-operations~.

If ever needed for a particular case, this can always be modeled this way as an
exception. Alternative approaches could be to branch off in
~business-operations~ in a fork and use that instead. Also having two versions
included would be an option.

The inclusion mechanism does not affect ~business-operations~, only the using
repository like ~b-ops~ would be affected, so that experimenting with the
approaches does not affect the shared repository in a negative way. The decision
how to use and include is completely inside the using repository.

**** Hint: Dependency Management

From the experimentation so far there is a clear hint that a mechanism for
dependency management will be eventually needed.

It seems that it should support a fine granular combination of building blocks
in some way. Somewhat similar to how modern package managers include a bunch of
libraries and support freezing / locking dependencies to a particular version.

It may be that a generic tool like Nix could help here to combine the fragments
in a way so that the result forms a directory tree which tooling like Kustomize,
Kluctl or Flux could as input.

This should be delayed as much as possible to better understand the real needs
first.

*** Kluctl testrun

Using Kluctl does put additional constraints around the setup which are mainly
relevant for development.

For the bootstrap case, it does not allow a Kustomization to refer to sources
outside of the project directory.

One reason seems to be that Kluctl first runs a "rendering" phase to apply
the Jinja 2 templating, and the result is then processed via Kustomize. The
local reference then simply does not resolve anymore.

It seems to walk up the directory tree to detect a git repository as the root to
copy files.

Trying to find out if there are approaches available which I did not yet
discover: https://github.com/kluctl/kluctl/discussions/1421.

**** Conclusion

- Usage for the bootstrap phase works nicely.
- Templating could allow to make the bootstrap already configurable in
  ~business-operations~.
- Unclear how a good local setup for fast iteration would look like. One option
  could be to consider a git submodule like approach.

*** First deployment via bootstrap playbook

With a stub inventory it is possible to run the bootstrap playbook into any
cluster. Used the ~dev-env~ cluster for a small scale test.

FluxCD did start up as intended, only Gitea did not deploy due to the missing
reference into the ~business-operations~ repository. At this stage this is
expected because soling this problem is one of the steps after the boostrap.

Only challenge left is that the Kustomization points into ~business-operations~
and needs some for of reference for this.

*** Dependencies

**** Overview

- ~ansible~ folder
  - Using currently the shell out of ~business-operations~
- ~nixos~ folder
  - Input of a Nix Flake.
  - Dev: Point to a local clone of ~business-operations~ with builtin tooling of
    Nix.
- ~bootstrap~ folder
  - Points into ~business-operations~ from a Kustomization.
  - Dev: Point to a local clone of ~business-operations~ instead.
- FluxCD
  - Has a ~GitRepository~ source pointing to a reference of
    ~business-operations~.

**** Approach for ~bootstrap~

This is all handled in the CLI, basically client side.

Tweaking the path in the Kustomization or even defining the overlay twice, once
as a dev variant to expect a local clone.

**** Approach for FluxCD

The ~GitRepository~ lives in ~b-ops~ and should pin down the exact reference as
tag or commit.

An update would be done by updating ~b-ops~ which sets the reference.

Development would benefit from a changed URL, either pointing into a fork of
~business-operations~ or even pointing to a fork in the internal Gitea instance.

The drawback of pointing into a reference like ~main~ or another branch name
would be that this is impossible (or at least fairly involved) to reproduce in
retrospect.

**** ~kluctl~ inspection

It does have the concept of overriding the git urls, this would solve the issue
in a similar way how nix is solving it with flake input overrides.

On the layer of it's custom ~Deployment~ object it does support git urls and oci
urls.

Apart from that most other parts are based on plain ~Kustomizations~.

***** Conclusion

The direct support for SOPS and the support for overriding git inputs would make
it a very good fit for the bootstrap part instead of plain ~kubectl~.

The ~nixpkgs~ version is up to date, using it would not involve a lot of tweaks.

**** Conclusion

- Start with depending on the local clone being next to the ~b-ops~ repo.
- Split and make it work.
- Test if kluctl can help here.
- The way how the dependency is pinned should ideally be the same, e.g.
  ~ansible~, ~nixos~ and ~kubernetes~ should all use the same version of the
  upstream repository.

*** Bootstrap folder

**** Research ~kluctl~

It has the concept of library deployments which can be imported. This could be
interesting.

See: https://kluctl.io/docs/kluctl/kluctl-libraries/

**** Content

***** Manifests

The bootstrap folder's *manifests* are not specific per instance. These can be used
directly out of ~business-operations~. The deployment of these is a one off.

#+begin_notes
The bootstrap seems to be specific to the usage of FluxCD.

It would not be needed if a push model would be used, like a ~kluctl~ setup
could do.
#+end_notes

***** Secrets

There are a few secrets deployed, these are all instance specific.

***** Kustomization

Tweaks components as needed. For development the storage class is currently
tweaked out.

*** FluxCD

**** GitRepository

The field ~spec.ref~ is most relevant. It allows to specify a commit reference
via ~spec.ref.commit~.

This could be one way to include ~business-operations~ into the local
repository. The ~GitRepository~ reference would be managed in the ~b-ops~
repository. This does need a Git commit per update and effectively makes
~business-operations~ a "submodule" of ~b-ops~.

Compare also ~.spec.recurseSubmodules~.

See: https://fluxcd.io/flux/components/source/gitrepositories/

**** External Artifact

- Allows to have artifacts produced by an external system.

See: https://fluxcd.io/flux/components/source/externalartifacts/

**** Artifact Generator

- Allows to compose multiple artifacts together.

See: https://fluxcd.io/flux/components/source/artifactgenerators/

*** Overview ~b-ops~

Looking at the following "phases" as described in the ~b-ops~ bootstrap overview:

- *Base infrastructure*
  - This is covered already from sprint 2.
- *Bootstrap*
  - This is about making FluxCD operational and providing a Git server so that
    FluxCD can start to take over.
  - Could aim for an empty cluster modeled after the ~dev-env~ setup.
  - Allows to "git push" into the cluster, and Flux will reconcile.
- *Base Apps*
  - Groups together the applications which are required so
    that the cluster is fully able to manage itself.
  - Examples: Vault, External Secrets, Gitlab, Volsync, Flux Webhook, Snapshot
    Controller, DNS, Rook-Ceph
- *Apps*
  - Everything else.

The current setup is already layered.

Only the layer *Apps* is expected to be customized.

*Base Apps* is still somewhat unclear, esp. since it does have "heavy" content
like Gitlab, Rook-Ceph and Vault.

Ideally the layered concept can stay to some degree.

The *Apps* part should eventually be split in some way, so that it is possible
to decide which apps to install. It should be possible to also bring one's own
apps without a need to be clued into the mono repository on the long run.

*** Bootstrap phase

**** Pre-conditions

- Cluster is working and can be accessed via ~kubectl~.

**** Steps

- Deploy ~bootstrap~ folder via ~kustomize~.
- Deploy the cluster's age key.
- Deploy Gitea bootstrap secret.
- Wait until Gitea has deen initialized and configured.
- Push repository into Gitea.
- Deploy cluster settings and secret settings.
- Kick off Flux by deploying ~flux/config~ via ~kustomize~.

Note: ~kustomize~ means ~kubectl apply --server-side --kustomize~.

*** Base apps phase

This is already purely done via Flux.

** Learnings and Insights

*** Kustomize and patching

Some applications are set up with common configuration and then adjustments for
the particular case.

One example is hajimari which supports a set of bookmarks to be configured
through its Helm values and a list of namespaces to observe.

The list of namespaces is a list of string values. With the strategic patches
such lists can only be replaced but not appended to.

As a workaround either copy the list or use the JSON patches instead.


** Closing Status

Outcome:
- Kubernetes layer extraction experimentally validated end-to-end.
- Dev cluster fully deployable from the split setup via minikube.
- Demo cluster deferred (ADR-0003: complete full split first).
- Acceptance cluster stood up on microVMs (ADR-0018).

What works:
- Submodule integration for all layers (nixos, ansible, kubernetes).
- Flux variable substitution carries through the split.
- Kluctl for bootstrap (templating, SOPS support).
- Backup/restore via Kustomize components (volumes and databases).

What needs improvement:
- Flux Kustomization patching across repos is fragile and hard to test locally.
- No way to render Helm chart results without a running cluster.
- Backup/restore revision handling is complex and error-prone.
- Dependency management across layers is manual.

Key insights:
- A CLI-based rendering tool would improve the development workflow.
- Kustomize components work well for cross-cutting concerns.
- The structure is not fully settled — doing the full split first will
  surface further refinements.

Stats:
- Started: 2026-02-15
- Closed: 2026-02-24
- Duration: 10 days
